@php($moduleSegment = request()->segment(2))
@php($currentModule = $moduleSegment ? \App\Models\Module::where('route_prefix', $moduleSegment)->where('is_active', true)->first() : null)

@if ($currentModule)
    @if (request()->is('app/dentaltrack*'))
        @include('dentaltrack::partials.nav', ['layout' => $layout ?? 'horizontal'])
    @elseif (request()->is('app/orgmatrix*'))
        @include('orgmatrix::partials.nav', ['layout' => $layout ?? 'horizontal'])
    @elseif (request()->is('app/visionflow*'))
        @include('visionflow::partials.nav', ['layout' => $layout ?? 'horizontal'])
    @elseif (request()->is('app/nurdu*'))
        @include('nurdu::partials.nav', ['layout' => $layout ?? 'horizontal'])
    @elseif (request()->is('app/cashcore*'))
        @include('cashcore::partials.nav', ['layout' => $layout ?? 'horizontal'])
    @elseif (request()->is('app/invoices*'))
        @include('invoicemaker::partials.nav', ['layout' => $layout ?? 'horizontal'])
    @elseif (request()->is('app/finance*'))
        @include('financialplatform::partials.nav', ['layout' => $layout ?? 'horizontal'])
    @elseif (request()->is('app/sweetspot*'))
        @include('sweetspot::partials.nav', ['layout' => $layout ?? 'horizontal'])
    @elseif (request()->is('app/timebutler*'))
        @include('timebutler::partials.nav', ['layout' => $layout ?? 'horizontal'])
    @elseif (request()->is('app/planhive*'))
        @include('planhive::partials.nav', ['layout' => $layout ?? 'horizontal'])
    @elseif (request()->is('app/sopbuilder*'))
        @include('sopbuilder::partials.nav', ['layout' => $layout ?? 'horizontal'])
    @elseif (request()->is('app/loopengine*'))
        @include('loopengine::partials.nav', ['layout' => $layout ?? 'horizontal'])
    @elseif (request()->is('app/focusmatrix*'))
        @include('focusmatrix::partials.nav', ['layout' => $layout ?? 'horizontal'])
    @elseif (request()->is('app/clusters*'))
        @include('clusterforge::partials.nav', ['layout' => $layout ?? 'horizontal'])
    @elseif (request()->is('app/leads*'))
        @include('leadquality::partials.nav', ['layout' => $layout ?? 'horizontal'])
    @endif
@endif
