<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><style>body{font-family:DejaVu Sans,sans-serif;color:#0f172a;font-size:12px}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #e2e8f0;text-align:left}.right{text-align:right}.muted{color:#64748b}.header{border-bottom:3px solid {{ $invoice->template?->primary_color ?? '#4f46e5' }};padding-bottom:18px;margin-bottom:24px}.total{font-size:16px;font-weight:bold}.grid{width:100%;margin-bottom:24px}.grid td{width:50%;vertical-align:top;border:0;padding:0}.summary{width:45%;margin-left:auto;margin-top:20px}.footer{margin-top:36px;padding-top:16px;border-top:1px solid #e2e8f0;color:#64748b}</style></head>
<body>
<div class="header"><table><tr><td style="border:0;padding:0"><h1>{{ $invoice->isEstimate() ? __('Estimate') : __('Invoice') }}</h1><div class="muted">{{ $invoice->invoice_number }}</div></td><td class="right" style="border:0;padding:0"><strong>{{ $invoice->profile->name }}</strong><br><span class="muted">{{ $invoice->profile->email }}<br>{{ $invoice->profile->phone }}</span></td></tr></table></div>
<table class="grid"><tr><td><strong>{{ __('Bill to') }}</strong><br>{{ $invoice->client->name }}<br>{{ $invoice->client->company_name }}<br>{!! nl2br(e($invoice->client->address)) !!}<br>{{ $invoice->client->email }}</td><td class="right"><strong>{{ __('Issue date') }}:</strong> {{ $invoice->invoice_date->format('M d, Y') }}<br><strong>{{ $invoice->isEstimate() ? __('Valid until') : __('Due date') }}:</strong> {{ $invoice->due_date->format('M d, Y') }}</td></tr></table>
<table><thead><tr><th>{{ __('Description') }}</th><th class="right">{{ __('Quantity') }}</th><th class="right">{{ __('Unit price') }}</th><th class="right">{{ __('Tax') }}</th><th class="right">{{ __('Total') }}</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr><td>{{ $item->description }}</td><td class="right">{{ $item->quantity }}</td><td class="right">{{ number_format((float) $item->unit_price, 2) }}</td><td class="right">{{ number_format((float) $item->tax_rate, 2) }}%</td><td class="right">{{ number_format((float) $item->total, 2) }}</td></tr>@endforeach</tbody></table>
<table class="summary"><tr><td>{{ __('Subtotal') }}</td><td class="right">{{ $invoice->currency_symbol }}{{ number_format((float) $invoice->subtotal, 2) }}</td></tr><tr><td>{{ __('Tax') }}</td><td class="right">{{ $invoice->currency_symbol }}{{ number_format((float) $invoice->tax_total, 2) }}</td></tr><tr><td>{{ __('Discount') }}</td><td class="right">-{{ $invoice->currency_symbol }}{{ number_format((float) $invoice->discount, 2) }}</td></tr><tr class="total"><td>{{ __('Total') }}</td><td class="right">{{ $invoice->currency_symbol }}{{ number_format((float) $invoice->grand_total, 2) }}</td></tr><tr><td>{{ __('Amount due') }}</td><td class="right">{{ $invoice->currency_symbol }}{{ number_format((float) $invoice->amount_due, 2) }}</td></tr></table>
@if($invoice->notes)<p><strong>{{ __('Notes') }}</strong><br>{!! nl2br(e($invoice->notes)) !!}</p>@endif
@if($invoice->payment_terms)<p><strong>{{ __('Payment terms') }}</strong><br>{!! nl2br(e($invoice->payment_terms)) !!}</p>@endif
<div class="footer">{{ $invoice->template?->footer_message }}<br>{{ $invoice->profile->bank_details }} @if($invoice->profile->iban)<br>IBAN: {{ $invoice->profile->iban }} @endif @if($invoice->profile->bic) · BIC: {{ $invoice->profile->bic }} @endif</div>
</body></html>
