<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="bg-slate-100">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $invoice->invoice_number }}</title><link href="https://fonts.bunny.net/css?family=figtree:400,500,600,700&display=swap" rel="stylesheet"/>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="min-h-screen font-sans text-slate-900">
<main class="mx-auto max-w-5xl p-4 sm:p-8">
    @if(session('success'))<div class="mb-4 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
    <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-10">
        <div class="flex flex-col gap-5 border-b border-slate-200 pb-7 sm:flex-row sm:justify-between"><div><p class="text-xs font-semibold uppercase tracking-wider text-indigo-600">{{ $invoice->isEstimate() ? __('Estimate') : __('Invoice') }}</p><h1 class="text-3xl font-bold">{{ $invoice->invoice_number }}</h1><p class="mt-1 text-slate-500">{{ ucfirst($invoice->status) }}</p></div><div class="sm:text-right"><p class="font-semibold">{{ $invoice->profile->name }}</p><p class="text-sm text-slate-500">{{ $invoice->profile->email }}<br>{{ $invoice->profile->phone }}</p></div></div>
        <div class="my-7 grid gap-6 sm:grid-cols-2"><div><p class="text-xs uppercase text-slate-500">{{ __('Bill to') }}</p><p class="mt-1 font-semibold">{{ $invoice->client->name }}</p><p class="text-sm text-slate-600">{{ $invoice->client->company_name }}<br>{!! nl2br(e($invoice->client->address)) !!}</p></div><div class="sm:text-right"><p><span class="text-slate-500">{{ __('Issue date') }}:</span> {{ $invoice->invoice_date->format('M d, Y') }}</p><p><span class="text-slate-500">{{ $invoice->isEstimate() ? __('Valid until') : __('Due date') }}:</span> {{ $invoice->due_date->format('M d, Y') }}</p></div></div>
        <div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-4 py-3">{{ __('Description') }}</th><th class="px-4 py-3 text-right">{{ __('Qty') }}</th><th class="px-4 py-3 text-right">{{ __('Price') }}</th><th class="px-4 py-3 text-right">{{ __('Total') }}</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($invoice->items as $item)<tr><td class="px-4 py-3">{{ $item->description }}</td><td class="px-4 py-3 text-right">{{ $item->quantity }}</td><td class="px-4 py-3 text-right">{{ number_format((float) $item->unit_price, 2) }}</td><td class="px-4 py-3 text-right font-medium">{{ number_format((float) $item->total, 2) }}</td></tr>@endforeach</tbody></table></div>
        <div class="ml-auto mt-6 max-w-sm space-y-2"><div class="flex justify-between"><span class="text-slate-500">{{ __('Total') }}</span><span class="text-xl font-bold">{{ $invoice->currency_symbol }}{{ number_format((float) $invoice->grand_total, 2) }}</span></div><div class="flex justify-between text-rose-700"><span>{{ __('Amount due') }}</span><span class="font-semibold">{{ $invoice->currency_symbol }}{{ number_format((float) $invoice->amount_due, 2) }}</span></div></div>
        <div class="mt-8 flex flex-wrap justify-end gap-3">
            <a href="{{ \Illuminate\Support\Facades\URL::temporarySignedRoute('invoicemaker.public.download', now()->addHour(), ['uuid' => $invoice->uuid]) }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium">{{ __('Download PDF') }}</a>
            @if($invoice->isEstimate() && !$invoice->accepted_at)<form method="POST" action="{{ \Illuminate\Support\Facades\URL::temporarySignedRoute('invoicemaker.public.approve', now()->addHour(), ['uuid' => $invoice->uuid]) }}">@csrf<button class="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">{{ __('Approve estimate') }}</button></form>@endif
            @if(!$invoice->isEstimate() && $invoice->amount_due > 0 && $invoice->profile->stripe_secret_key)<form method="POST" action="{{ \Illuminate\Support\Facades\URL::temporarySignedRoute('invoicemaker.public.payment.checkout', now()->addHour(), ['uuid' => $invoice->uuid]) }}">@csrf<button class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">{{ __('Pay securely') }}</button></form>@endif
        </div>
    </section>
    <section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-semibold">{{ __('Comments') }}</h2><div class="my-4 space-y-3">@foreach($invoice->comments->where('is_internal', false) as $comment)<div class="rounded-lg bg-slate-50 p-3"><p class="text-xs text-slate-500">{{ $comment->author_name }} · {{ $comment->created_at->diffForHumans() }}</p><p class="mt-1 text-sm">{{ $comment->comment }}</p></div>@endforeach</div><form method="POST" action="{{ \Illuminate\Support\Facades\URL::temporarySignedRoute('invoicemaker.public.comment', now()->addHour(), ['uuid' => $invoice->uuid]) }}" class="flex gap-2">@csrf<input name="comment" required maxlength="5000" class="flex-1 rounded-lg border-slate-300 text-sm" placeholder="{{ __('Add a comment') }}"><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">{{ __('Send') }}</button></form>@if($invoice->isEstimate())<form method="POST" action="{{ \Illuminate\Support\Facades\URL::temporarySignedRoute('invoicemaker.public.revision', now()->addHour(), ['uuid' => $invoice->uuid]) }}" class="mt-3 flex gap-2">@csrf<input name="comment" required maxlength="5000" class="flex-1 rounded-lg border-slate-300 text-sm" placeholder="{{ __('Describe the requested revision') }}"><button class="rounded-lg border border-amber-300 px-4 py-2 text-sm font-semibold text-amber-700">{{ __('Request revision') }}</button></form>@endif</section>
</main>
</body></html>
