<div>
    @include('invoicemaker::partials.nav')
    <div class="mb-6"><h1 class="text-2xl font-bold text-slate-900">{{ __('Invoice settings') }}</h1><p class="text-sm text-slate-500">{{ __('Team billing identity, numbering, payment terms, reminders, and customer-payment credentials.') }}</p></div>
    <form wire:submit="save" class="space-y-6">
        <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="mb-5 font-semibold text-slate-900">{{ __('Business identity') }}</h2><div class="grid gap-5 sm:grid-cols-2">@foreach(['name' => __('Name'), 'email' => __('Email'), 'phone' => __('Phone'), 'tax_number' => __('Tax number'), 'currency' => __('Currency'), 'timezone' => __('Timezone'), 'iban' => __('IBAN'), 'bic' => __('BIC')] as $field => $label)<label><span class="text-sm text-slate-600">{{ $label }}</span><input wire:model="{{ $field }}" class="mt-1 w-full rounded-lg border-slate-300 text-sm">@error($field)<span class="text-xs text-rose-600">{{ $message }}</span>@enderror</label>@endforeach</div><div class="mt-5 grid gap-5 sm:grid-cols-2"><label><span class="text-sm text-slate-600">{{ __('Address') }}</span><textarea wire:model="address" rows="4" class="mt-1 w-full rounded-lg border-slate-300 text-sm"></textarea></label><label><span class="text-sm text-slate-600">{{ __('Bank details') }}</span><textarea wire:model="bank_details" rows="4" class="mt-1 w-full rounded-lg border-slate-300 text-sm"></textarea></label></div></section>
        <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="mb-5 font-semibold text-slate-900">{{ __('Numbering & terms') }}</h2><div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><label><span class="text-sm text-slate-600">{{ __('Invoice prefix') }}</span><input wire:model="invoice_number_prefix" class="mt-1 w-full rounded-lg border-slate-300 text-sm"></label><label><span class="text-sm text-slate-600">{{ __('Estimate prefix') }}</span><input wire:model="estimate_number_prefix" class="mt-1 w-full rounded-lg border-slate-300 text-sm"></label><label><span class="text-sm text-slate-600">{{ __('Payment days') }}</span><input wire:model="payment_terms_days" type="number" class="mt-1 w-full rounded-lg border-slate-300 text-sm"></label><label><span class="text-sm text-slate-600">{{ __('Late fee %') }}</span><input wire:model="late_fee_percentage" type="number" step="0.01" class="mt-1 w-full rounded-lg border-slate-300 text-sm"></label></div><label class="mt-5 block"><span class="text-sm text-slate-600">{{ __('Default payment terms') }}</span><textarea wire:model="default_payment_terms" rows="3" class="mt-1 w-full rounded-lg border-slate-300 text-sm"></textarea></label><div class="mt-5 flex flex-wrap items-center gap-6"><label class="flex items-center gap-2 text-sm"><input wire:model="enable_automated_reminders" type="checkbox" class="rounded border-slate-300 text-indigo-600"> {{ __('Enable automated reminders') }}</label><label class="flex items-center gap-2 text-sm">{{ __('Reminder every') }} <input wire:model="reminder_days_interval" type="number" class="w-20 rounded-lg border-slate-300 text-sm"> {{ __('days') }}</label></div></section>
        <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-semibold text-slate-900">{{ __('Customer invoice payments') }}</h2><p class="mb-5 text-sm text-slate-500">{{ __('These Stripe keys collect customer invoice payments and are separate from Allocore Suite subscription billing.') }}</p><div class="grid gap-5 sm:grid-cols-2"><label><span class="text-sm text-slate-600">{{ __('Stripe publishable key') }}</span><input wire:model="stripe_public_key" class="mt-1 w-full rounded-lg border-slate-300 text-sm"></label><label><span class="text-sm text-slate-600">{{ __('Stripe secret key') }}</span><input wire:model="stripe_secret_key" type="password" placeholder="{{ __('Leave blank to keep existing key') }}" class="mt-1 w-full rounded-lg border-slate-300 text-sm"></label></div></section>
        <div class="flex justify-end"><button class="rounded-lg bg-indigo-600 px-5 py-2 text-sm font-semibold text-white">{{ __('Save settings') }}</button></div>
    </form>
</div>
